-- MySQL Script generated by MySQL Workbench
-- Fri Jun  7 18:53:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbMovies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbMovies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbMovies` DEFAULT CHARACTER SET utf8 ;
USE `dbMovies` ;

-- -----------------------------------------------------
-- Table `dbMovies`.`tbUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMovies`.`tbUser` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nmUser` VARCHAR(60) NOT NULL,
  `emUser` VARCHAR(70) NOT NULL,
  `passUser` VARCHAR(15) NOT NULL,
  `CEP` VARCHAR(8) NULL,
  `logradouro` VARCHAR(45) NULL,
  `nrUser` INT UNSIGNED NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` CHAR(2) NULL,
  `compUser` VARCHAR(15) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `emUser_UNIQUE` (`emUser` ASC) VISIBLE
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbMovies`.`tbMovies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMovies`.`tbMovies` (
  `idMovie` INT NOT NULL AUTO_INCREMENT,
  `nmMovie` VARCHAR(100) NOT NULL,
  `dirMovie` VARCHAR(60) NOT NULL,
  `anoMovie` DATE NULL,
  `ntIMDB` DECIMAL(5,3) NULL,
  PRIMARY KEY (`idMovie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbMovies`.`tbLocacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbMovies`.`tbLocacao` (
  `fkUser` INT NOT NULL,
  `fkMovie` INT NOT NULL,
  `dtLoca` DATE NOT NULL,
  PRIMARY KEY (`fkUser`, `fkMovie`),
  INDEX `fk_tbUser_has_tbMovies_tbMovies1_idx` (`fkMovie` ASC) VISIBLE,
  INDEX `fk_tbUser_has_tbMovies_tbUser1_idx` (`fkUser` ASC) VISIBLE,
  CONSTRAINT `fk_tbUser_has_tbMovies_tbUser1`
    FOREIGN KEY (`fkUser`)
    REFERENCES `dbMovies`.`tbUser` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbUser_has_tbMovies_tbMovies1`
    FOREIGN KEY (`fkMovie`)
    REFERENCES `dbMovies`.`tbMovies` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
